ALTER TABLE "tblSite" ALTER COLUMN "Record_No" TYPE INTEGER;
ALTER TABLE "tblSite" ALTER "Record_No" ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL('"tblSite_Record_No_seq"', (SELECT MAX("Record_No") FROM "tblSite")); 

ALTER TABLE "tblPMs" ALTER COLUMN "Record_No" TYPE INTEGER;
ALTER TABLE "tblPMs" ALTER "Record_No" ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL('"tblPMs_Record_No_seq"', (SELECT MAX("Record_No") FROM "tblPMs")); 

ALTER TABLE "zLU_Perf" ALTER COLUMN "Record_No" TYPE INTEGER;
ALTER TABLE "zLU_Perf" ALTER "Record_No" ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL('"zLU_Perf_Record_No_seq"', (SELECT MAX("Record_No") FROM "zLU_Perf")); 

ALTER TABLE "zLU_tblAppProf" ALTER COLUMN "Record_No" TYPE INTEGER;
ALTER TABLE "zLU_tblAppProf" ALTER "Record_No" ADD GENERATED ALWAYS AS IDENTITY;
SELECT SETVAL('"zLU_tblAppProf_Record_No_seq"', (SELECT MAX("Record_No") FROM "zLU_tblAppProf"));
